# Subsetting

In [3]:
import numpy as np
import pandas as pd

In [4]:
from numpy.random import randint as ri

In [88]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("matrix of random 2 digit number\n----------------------------------\n",mat)

matrix of random 2 digit number
----------------------------------
 [[96 59 29 11 85]
 [93 42 68 98 12]
 [49 60 67 41 68]]


In [89]:
print("Element greater than 50\n",mat[mat>50])

Element greater than 50
 [96 59 85 93 68 98 60 67 68]


In [90]:
mat>50

array([[ True,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False,  True]])

# Slicing

In [91]:
mat=np.array([[11,12,13],[21,22,23],[31,32,33]])
print("original matrix\n-----------------------------------")
print(mat)

original matrix
-----------------------------------
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [92]:
mat_slice=mat[:2,:2]
print("\nsliced matrix")
print(mat_slice)
print("\nchange the slice matrix")


sliced matrix
[[11 12]
 [21 22]]

change the slice matrix


In [93]:
mat_slice[0,0]=1000
print(mat_slice)


[[1000   12]
 [  21   22]]


In [94]:
print("\n but the original matrix?WHOA!It got changed too!")
print(mat)


 but the original matrix?WHOA!It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [95]:
#little different way to create a copy of the sliced matrix
print("\n Doing it again little differently now-----\n")
mat=np.array([[11,12,13],[21,22,23],[21,32,33]])
print("original matrix")
print(mat)


 Doing it again little differently now-----

original matrix
[[11 12 13]
 [21 22 23]
 [21 32 33]]


# Universal function

In [96]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n1st matrix of random single digit numbers\n----------------------------------------------\n",mat1)
print("\n2nd matrix of random single digit numbers\n----------------------------------------------\n",mat2)


1st matrix of random single digit numbers
----------------------------------------------
 [[2 2 3]
 [4 1 2]
 [5 4 8]]

2nd matrix of random single digit numbers
----------------------------------------------
 [[7 1 5]
 [4 3 9]
 [3 4 7]]


In [97]:
print("\nAddition\n----------------------------\n",mat1+mat2)
print("\nMultiplication\n------------------------\n",mat1*mat2)


Addition
----------------------------
 [[ 9  3  8]
 [ 8  4 11]
 [ 8  8 15]]

Multiplication
------------------------
 [[14  2 15]
 [16  3 18]
 [15 16 56]]


In [98]:
print("\nDivision\n----------------------\n",mat1/mat2)



Division
----------------------
 [[0.28571429 2.         0.6       ]
 [1.         0.33333333 0.22222222]
 [1.66666667 1.         1.14285714]]


In [99]:
print("\nLInear combination:3*a - 2*b\n------------------------\n",3*mat1-2*mat2)


LInear combination:3*a - 2*b
------------------------
 [[ -8   4  -1]
 [  4  -3 -12]
 [  9   4  10]]


In [100]:
print("\nAddition of a scalor(100)\n------------------------------\n",100+mat1)
new_mat=100+mat1


Addition of a scalor(100)
------------------------------
 [[102 102 103]
 [104 101 102]
 [105 104 108]]


In [101]:
new_mat

array([[102, 102, 103],
       [104, 101, 102],
       [105, 104, 108]])

In [102]:
print("\nExponential,matrix cubed here\n-------------------------------------------\n ",mat1**3)
print("\n Exponential,sr-root using pow function\n--------------------------------------\n",pow(mat1,0.5))


Exponential,matrix cubed here
-------------------------------------------
  [[  8   8  27]
 [ 64   1   8]
 [125  64 512]]

 Exponential,sr-root using pow function
--------------------------------------
 [[1.41421356 1.41421356 1.73205081]
 [2.         1.         1.41421356]
 [2.23606798 2.         2.82842712]]


In [103]:
mat1

array([[2, 2, 3],
       [4, 1, 2],
       [5, 4, 8]])

In [104]:
mat2

array([[7, 1, 5],
       [4, 3, 9],
       [3, 4, 7]])

# Broadcasting

In [105]:
Start=np.zeros((3,3))
print(Start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [106]:
#create a rank 1 ndarray with 3 values 
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [107]:
#add to each row of 'start'using broadcasting
y=Start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [108]:
#create an ndaarray which is 4% 1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [109]:
Start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
#This will just broadcasting in both dimensions 
add_scalor=np.array([100])
print(Start+add_scalor)

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


# Array math

In [111]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n1st matrix of random single digit number\n-----------------\n",mat1)
print("\n2nd matrix of random single digit number\n-----------------\n",mat2)



1st matrix of random single digit number
-----------------
 [[2 5 9]
 [2 9 8]
 [3 2 4]]

2nd matrix of random single digit number
-----------------
 [[4 2 5]
 [6 1 6]
 [9 7 6]]


In [112]:
print("\nsq-root of 1st matrix using np\n-------------------------------------\n",np.sqrt(mat1))


sq-root of 1st matrix using np
-------------------------------------
 [[1.41421356 2.23606798 3.        ]
 [1.41421356 3.         2.82842712]
 [1.73205081 1.41421356 2.        ]]


In [113]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n",np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[7.38905610e+00 1.48413159e+02 8.10308393e+03]
 [7.38905610e+00 8.10308393e+03 2.98095799e+03]
 [2.00855369e+01 7.38905610e+00 5.45981500e+01]]


In [114]:
print("\n10 base logarithm on 1st matrix using np\n",'-'*50,"\n",np.log10(mat1))


10 base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.30103    0.69897    0.95424251]
 [0.30103    0.95424251 0.90308999]
 [0.47712125 0.30103    0.60205999]]


In [115]:
np.log(3)

1.0986122886681098

# Pandas

In [116]:
import numpy as np
import pandas as pd

In [117]:
ser=pd.Series()
ser

<ipython-input-117-256366896314>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser=pd.Series()


Series([], dtype: float64)

In [118]:
ser=pd.Series([0,10,20,30,40,50,60,70,80,90,])
ser

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64

In [119]:
#Notice Datatype
ser=pd.Series([20,15.7,"10"])
ser

0      20
1    15.7
2      10
dtype: object

In [120]:
#Notice datatype
ser=pd.Series([20,15.7])
ser

0    20.0
1    15.7
dtype: float64

Create dictionary

In [121]:
dict={'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]}
df=pd.DataFrame(dict)
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [122]:
#Add new column and add values into it
df['State']="ca nv az".split()

In [123]:
df

a  b  c State
0  1  4  7    ca
1  2  5  8    nv
2  3  6  9    az

In [124]:
#How to create nan values and its manipulation
dict = {'a':[1,2,np.nan],'b':[5,np.nan,np.nan],'c':[1,2,3]}

In [125]:
df=pd.DataFrame(dict)
df

a    b  c
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [126]:
df['States']= "CA NV AZ".split()
df

a    b  c States
0  1.0  5.0  1     CA
1  2.0  NaN  2     NV
2  NaN  NaN  3     AZ

In [127]:
print("\nDropping any column with a nan value\n",'-'*35,sep='')
print(df.dropna(axis=1))


Dropping any column with a nan value
-----------------------------------
   c States
0  1     CA
1  2     NV
2  3     AZ


In [128]:
df

a    b  c States
0  1.0  5.0  1     CA
1  2.0  NaN  2     NV
2  NaN  NaN  3     AZ

In [129]:
print("\nFilling values with a default value\n",'-'*35,sep='')
print(df.fillna(value=20))


Filling values with a default value
-----------------------------------
      a     b  c States
0   1.0   5.0  1     CA
1   2.0  20.0  2     NV
2  20.0  20.0  3     AZ


In [130]:
df

a    b  c States
0  1.0  5.0  1     CA
1  2.0  NaN  2     NV
2  NaN  NaN  3     AZ

In [131]:
print("\nDropping any rows with a nan values\n",'-'*35)
print(df.dropna(axis=0))


Dropping any rows with a nan values
 -----------------------------------
     a    b  c States
0  1.0  5.0  1     CA


In [132]:
#dataframe remains some will see how we can save the dataframe later
df

a    b  c States
0  1.0  5.0  1     CA
1  2.0  NaN  2     NV
2  NaN  NaN  3     AZ

In [133]:
print(" \nFilling value with a computed value(mean of colume A here)\n",'-'*60,sep='')
print(df.fillna(value=df['a'].mean()))

 
Filling value with a computed value(mean of colume A here)
------------------------------------------------------------
     a    b  c States
0  1.0  5.0  1     CA
1  2.0  1.5  2     NV
2  1.5  1.5  3     AZ


In [134]:
#Create dataframe
data={'company':['google','google','MSFT','MSFT','FB','FB'],
     'person':['sam','charlie','ram','dhyan','np','jp'],
     'sales':[200,120,340,124,243,350]}
df=pd.DataFrame(data)
df

company   person  sales
0  google      sam    200
1  google  charlie    120
2    MSFT      ram    340
3    MSFT    dhyan    124
4      FB       np    243
5      FB       jp    350

In [135]:
bycomp=df.groupby('company')
print("\nGrouping by 'company'column and listing mean sales\n",'-'*55,sep='')
print(bycomp.mean())


Grouping by 'company'column and listing mean sales
-------------------------------------------------------
         sales
company       
FB       296.5
MSFT     232.0
google   160.0


In [7]:
#Merging two data frames
#Creating data frames
df1=pd.DataFrame({'a':['a0','a1','a2','a3'],
                 'b':['b0','b1','b2','b3'],
                 'c':['c0','c1','c2','c3'],
                 'd':['d0','d1','d2','d3']},
                index=[0,1,2,3])

df2=pd.DataFrame({'a':['a4','a5','a6','a7'],
                 'b':['b4','b5','b6','b7'],
                 'c':['c4','c5','c6','c7'],
                 'd':['d4','d5','d6','d7']},
                index=[4,5,6,7])

df3=pd.DataFrame({'a':['a8','a9','a10','a11'],
                 'b':['b8','b9','b10','b11'],
                 'c':['c8','c9','c10','c11'],
                 'd':['d8','d9','d10','d11']},
                index=[8,9,10,11])


In [8]:
print("\nThe DataFrame number 1\n",'-'*30,sep='')
print(df1)


The DataFrame number 1
------------------------------
    a   b   c   d
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3


In [9]:
print("\nThe DataFrame number 2\n",'-'*30,sep='')
print(df2)


The DataFrame number 2
------------------------------
    a   b   c   d
4  a4  b4  c4  d4
5  a5  b5  c5  d5
6  a6  b6  c6  d6
7  a7  b7  c7  d7


In [10]:
print("\nThe DataFrame number 3\n",'-'*30,sep='')
print(df3)


The DataFrame number 3
------------------------------
      a    b    c    d
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11


In [11]:
#concatenation
df_cat1=pd.concat([df1,df2,df3],axis=0)
print("\nAfter concatenation along row\n",'-'*45,sep='')
print(df_cat1)


After concatenation along row
---------------------------------------------
      a    b    c    d
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11


In [12]:
df_cat1=pd.concat([df1,df2,df3],axis=1)
print("\nAfter concatenation along column\n",'-'*45,sep='')
print(df_cat1)


After concatenation along column
---------------------------------------------
      a    b    c    d    a    b    c    d    a    b    c    d
0    a0   b0   c0   d0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    a2   b2   c2   d2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   a5   b5   c5   d5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   a7   b7   c7   d7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   a8   b8   c8   d8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   a9   b9   c9   d9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  a10  b10  c10  d10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  a11  b11  c11  d11


In [14]:
df_cat1.fillna(value=0,inplace=True)
print("\nAfter filling missing value with zero\n",'-'*60,sep='')
print(df_cat1)


After filling missing value with zero
------------------------------------------------------------
     a   b   c   d   a   b   c   d    a    b    c    d
0   a0  b0  c0  d0   0   0   0   0    0    0    0    0
1   a1  b1  c1  d1   0   0   0   0    0    0    0    0
2   a2  b2  c2  d2   0   0   0   0    0    0    0    0
3   a3  b3  c3  d3   0   0   0   0    0    0    0    0
4    0   0   0   0  a4  b4  c4  d4    0    0    0    0
5    0   0   0   0  a5  b5  c5  d5    0    0    0    0
6    0   0   0   0  a6  b6  c6  d6    0    0    0    0
7    0   0   0   0  a7  b7  c7  d7    0    0    0    0
8    0   0   0   0   0   0   0   0   a8   b8   c8   d8
9    0   0   0   0   0   0   0   0   a9   b9   c9   d9
10   0   0   0   0   0   0   0   0  a10  b10  c10  d10
11   0   0   0   0   0   0   0   0  a11  b11  c11  d11
