# Matrix Creation

In [2]:
import numpy as np


In [3]:
print("vector of zeroes\n-------------------")
print(np.zeros(100))

vector of zeroes
-------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [5]:
print("matrix of zeroes\n-------------------")
print(np.zeros((4,3)))

matrix of zeroes
-------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print("vector of one's\n----------------------")
print(np.ones(10))

vector of one's
----------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
print("matrix of one's\n-------------------")
print(np.ones((4,3)))

matrix of one's
-------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print("matrix of 5's \n-------------------------------------")
print(15*np.ones((10,5)))

matrix of 5's 
-------------------------------------
[[15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15.]]


In [10]:
mat1=np.eye(5)
print("Identity matrix of dimension",mat1.shape)
print(mat1)

Identity matrix of dimension (5, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
np.linspace(2.0,3.0, num=4, endpoint=True)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [15]:
#restep is the stepsize seperating from samples
np.linspace(2.23456,10.34556443,num=50,retstep=True)

(array([ 2.23456   ,  2.4000907 ,  2.56562141,  2.73115211,  2.89668281,
         3.06221351,  3.22774422,  3.39327492,  3.55880562,  3.72433632,
         3.88986703,  4.05539773,  4.22092843,  4.38645913,  4.55198984,
         4.71752054,  4.88305124,  5.04858195,  5.21411265,  5.37964335,
         5.54517405,  5.71070476,  5.87623546,  6.04176616,  6.20729686,
         6.37282757,  6.53835827,  6.70388897,  6.86941967,  7.03495038,
         7.20048108,  7.36601178,  7.53154248,  7.69707319,  7.86260389,
         8.02813459,  8.1936653 ,  8.359196  ,  8.5247267 ,  8.6902574 ,
         8.85578811,  9.02131881,  9.18684951,  9.35238021,  9.51791092,
         9.68344162,  9.84897232, 10.01450302, 10.18003373, 10.34556443]),
 0.16553070265306122)

In [24]:
np.logspace(2.0,3.0,num=12,endpoint=True)

array([ 100.        ,  123.28467394,  151.9911083 ,  187.38174229,
        231.01297001,  284.80358684,  351.11917342,  432.87612811,
        533.66992312,  657.93322466,  811.13083079, 1000.        ])

Construct diagonal matrix

In [34]:
x = np.arange(30).reshape(((6,5)))

In [35]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
np.diag(x)

array([ 0,  6, 12, 18, 24])

# Random number generation

In [43]:
print("Random number generation(from uniform distribution)\n----------------------------------------------------------")
print(np.random.rand(10,5))

Random number generation(from uniform distribution)
----------------------------------------------------------
[[0.38889575 0.48708691 0.43817733 0.42988505 0.44512435]
 [0.86326173 0.60586478 0.58803157 0.61075376 0.11295438]
 [0.02487708 0.18737795 0.98192548 0.66844432 0.19442528]
 [0.5222933  0.43367833 0.16452157 0.35883842 0.63343092]
 [0.08266666 0.94928937 0.3718349  0.89980623 0.24485161]
 [0.23988654 0.03012711 0.19955671 0.25804227 0.38826474]
 [0.92005776 0.20890924 0.19035265 0.02033974 0.68319822]
 [0.96971258 0.22050316 0.73895744 0.41951086 0.29984707]
 [0.15806925 0.48235551 0.39883565 0.93214463 0.98873104]
 [0.32270178 0.61393986 0.18748711 0.64168554 0.49633046]]


In [55]:
print("numbers from normal distribution with zero mean and standard deviation 1 i.e standard normal")
print(np.random.randn(10,2))

numbers from normal distribution with zero mean and standard deviation 1 i.e standard normal
[[ 0.59935892 -0.0908554 ]
 [ 0.38130797  0.58599097]
 [-1.03676558 -0.44628149]
 [ 0.06656874 -0.95430519]
 [ 1.0728869   0.56880287]
 [ 0.69283088  0.45997668]
 [ 0.06339641 -0.64122345]
 [ 0.54480329  0.91764341]
 [ 0.12195781  0.38659398]
 [ 0.2741385   0.64130157]]


In [47]:
print("random integer vector:",
      np.random.randint(1,6,10))

random integer vector: [3 4 1 4 1 4 5 3 4 2]


In [54]:
print("\nRandom integer matrix")
print(np.random.randint(1,30,(4,4)))


Random integer matrix
[[23 27 20 26]
 [27  4 11 29]
 [17  8 10 14]
 [ 7 10 23 27]]


In [56]:
print("\n20 samples drawn from a dice throw:",
     np.random.randint(1,7,20))


20 samples drawn from a dice throw: [1 1 1 2 6 5 3 6 5 5 4 3 5 6 2 6 2 2 3 1]


# Reshapping

In [15]:
import numpy as np


In [16]:
from numpy.random import randint as ri


In [17]:
a = ri(1,99,30)
b = a.reshape(2,3,5)
c = a.reshape(5,6)


In [18]:
a

array([87, 84, 73, 40, 34, 62, 36, 11, 85, 31, 58, 15, 11, 31, 69, 15, 65,
       81, 36, 17, 38, 93, 70, 79, 74, 24, 73, 56, 33,  1])

In [19]:

b

array([[[87, 84, 73, 40, 34],
        [62, 36, 11, 85, 31],
        [58, 15, 11, 31, 69]],

       [[15, 65, 81, 36, 17],
        [38, 93, 70, 79, 74],
        [24, 73, 56, 33,  1]]])

In [20]:
c

array([[87, 84, 73, 40, 34, 62],
       [36, 11, 85, 31, 58, 15],
       [11, 31, 69, 15, 65, 81],
       [36, 17, 38, 93, 70, 79],
       [74, 24, 73, 56, 33,  1]])

In [21]:
print("shape of a:",a.shape)
print("shape of b:",b.shape)
print("shape of c:",c.shape)

shape of a: (30,)
shape of b: (2, 3, 5)
shape of c: (5, 6)


In [22]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [87 84 73 40 34 62 36 11 85 31 58 15 11 31 69 15 65 81 36 17 38 93 70 79
 74 24 73 56 33  1] 
 --------------------

b looks like
 -------------------- 
 [[[87 84 73 40 34]
  [62 36 11 85 31]
  [58 15 11 31 69]]

 [[15 65 81 36 17]
  [38 93 70 79 74]
  [24 73 56 33  1]]] 
 --------------------

c looks like
 -------------------- 
 [[87 84 73 40 34 62]
 [36 11 85 31 58 15]
 [11 31 69 15 65 81]
 [36 17 38 93 70 79]
 [74 24 73 56 33  1]] 
 --------------------


In [27]:
a=ri(1,100,10)#vector of random integers
print("\nvector of random integers\n",'-'*50,"\n",a)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(a,kind = 'quicksort'))


vector of random integers
 -------------------------------------------------- 
 [95 83  4 43 84 66 60 41 31 17]

Here is the sorted vector
 -------------------------------------------------- 
 [ 4 17 31 41 43 60 66 83 84 95]


In [28]:
M=ri(1,100,25).reshape(5,5)#matrix of random integers
print("\n5x5 matrix of random integer\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M))
print("\nHere is the sorted matrix along each column\n","\n",np.sort(M,axis=0,kind = 'mergesort'))


5x5 matrix of random integer
 -------------------------------------------------- 
 [[84 63 69 90 55]
 [75 40  7 20 46]
 [27 73 59 53 26]
 [76 77 10 44 21]
 [16 51 87  6 24]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[55 63 69 84 90]
 [ 7 20 40 46 75]
 [26 27 53 59 73]
 [10 21 44 76 77]
 [ 6 16 24 51 87]]

Here is the sorted matrix along each column
 
 [[16 40  7  6 21]
 [27 51 10 20 24]
 [75 63 59 44 26]
 [76 73 69 53 46]
 [84 77 87 90 55]]


In [29]:
M

array([[84, 63, 69, 90, 55],
       [75, 40,  7, 20, 46],
       [27, 73, 59, 53, 26],
       [76, 77, 10, 44, 21],
       [16, 51, 87,  6, 24]])

In [30]:
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0,kind = 'mergesort'))


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[16 40  7  6 21]
 [27 51 10 20 24]
 [75 63 59 44 26]
 [76 73 69 53 46]
 [84 77 87 90 55]]


In [31]:
a

array([95, 83,  4, 43, 84, 66, 60, 41, 31, 17])

In [32]:
b

array([[[87, 84, 73, 40, 34],
        [62, 36, 11, 85, 31],
        [58, 15, 11, 31, 69]],

       [[15, 65, 81, 36, 17],
        [38, 93, 70, 79, 74],
        [24, 73, 56, 33,  1]]])

In [35]:
print("min of a:",a.min())

min of a: 4


In [36]:
print("max of b:",b.max())

max of b: 93


# Indexing and slicing

In [46]:
arr=np.arange(1,11)
print("Array",arr)

Array [ 1  2  3  4  5  6  7  8  9 10]


In [47]:
print("element at 7th index is:",arr[7])

element at 7th index is: 8


In [48]:
print("element from 3rd to 5th index are:",arr[3:6])


element from 3rd to 5th index are: [4 5 6]


In [49]:
print("Element up to 4th index are:",arr[2:5])
abc=arr[4:]

Element up to 4th index are: [3 4 5]


In [50]:
abc

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
print("Elements from last backward are:",arr[-1::-2])

Elements from last backward are: [10  8  6  4  2]


In [55]:
print("7 element from last backward are:",arr[-1:-8:-1])

7 element from last backward are: [10  9  8  7  6  5  4]


In [57]:
arr=np.arange(1,21,2)
print("new array:",arr)

new array: [ 1  3  5  7  9 11 13 15 17 19]


In [58]:
print("Element at 2nd,4th and 9th index are:",arr[[2,4,9]])

Element at 2nd,4th and 9th index are: [ 5  9 19]


In [62]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
print("\n double bracket indexing\n--------------------------------\n")
print("Element in row index 1 and column index 2:",mat[2][1])


 double bracket indexing
--------------------------------

Element in row index 1 and column index 2: 8


In [67]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
print("Entire row at index2:",mat[2])
print("Entire column at index3:",mat[:,1:])

Entire row at index2: [7 8 9]
Entire column at index3: [[2 3]
 [5 6]
 [8 9]]


In [78]:
print("\n subsetting sub matrics\n---------------------------------")
print("Matrix with row indexes 1 and 2 and column indexes 3 and 4\n",mat[1:2,1:2])


 subsetting sub matrics
---------------------------------
Matrix with row indexes 1 and 2 and column indexes 3 and 4
 [[5]]


In [73]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
print(mat[0:2,[1,2]])

[[2 3]
 [5 6]]
